[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
camino = "1.1.6"

[dev-dependencies]
pretty_assertions = "1.4.0"
